#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
# your temporary directory uses tmpfs

if [ -e /etc/init/opentsdb.conf ]; then
  juju-log "Stopping opentsdb"
  service opentsdb start
fi
